name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # Specify the Ruby version you need

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Ruby Scriptss
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        ruby ruby_scripts/affiliations_generator.rb
        ruby ruby_scripts/contact_generator.rb
        ruby ruby_scripts/course_page_generator.rb
        ruby ruby_scripts/office_hours_generator.rb
        ruby ruby_scripts/people_generator.rb
        if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Committing and pushing changes."
            git add .
            git commit -m 'Pushing Ruby Scripts outputs'
            git push origin main
        else
            echo "No changes detected. No commit or push performed."
        fi

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./_site
